apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-challenge-deployment
  labels:
    app: node-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-challenge
  template:
    metadata:
      labels:
        app: node-challenge
    spec:
      containers:
      - name: node-challenge
        image: node-challenge:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: NAME
          value: Chris
