apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-challenge-pv
spec:
  capacity:
    storage: 512m
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/node-challenge-pv
  storageClassName: shared
